### ISSUE TITLE
Make image uploader dynamic in nature

### ISSUE THREAD

**Issue by shubhank-saxena** [shubhank-saxena/flowerClassification#6]
It should display the name of the image that is being uploaded!

**Comment by DivjyotSingh** [comment]
I would like to work on this issue @shubhank-saxena

**Comment by shubhank-saxena** [comment]
@DivjyotSingh please go ahead!

**Comment by DivjyotSingh** [comment]
@shubhank-saxena I have a ques whether we would take a single image as input or multiple images

**Comment by shubhank-saxena** [comment]
@DivjyotSingh single image upload
